import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
    initial: 'ru',
    save: process.env.NODE_ENV === 'production',
    languages: [
        new MLanguage('ru').create({
            callBack: 'Заказать звонок',
            title: 'Начните свой&nbsp;бизнес <br>в&nbsp;ОАЭ',
            subtitle: 'Узнайте, как открыть компанию в&nbsp;ОАЭ из любой точки мира — получите расчёт затрат и&nbsp;перечень требований в&nbsp;подарок',
            btn_home: 'Оставить заявку',
            btn_send: 'Оставить заявку',
            site_link: 'Перейти на сайт',
            header_step: 'Вопрос {0}',
            header_step_cont: 'Контакты',
            header_thank: 'Спасибо',
            header_title_1: 'Какая лицензия вам необходима?',
            header_title_2: 'Информация об учредителе',
            header_title_3: 'Информация о директоре',
            header_title_4: 'Резидентская виза ОАЭ для&nbsp;учредителей и&nbsp;персонала',
            header_title_5: 'Когда планируете подать заявку на регистрацию компании в ОАЭ?',
            header_title_6: 'Расскажите нам о планируемом бизнесе в ОАЭ',
            header_title_7: 'Организационные вопросы',
            header_title_8: 'Получите расчёт затрат и перечень требований в подарок',
            q1_v1: 'Партнёрство с ограниченной ответственностью',
            q1_v2: 'Филиал или представительство иностранной компании',
            q1_v3: 'Компания в Свободной Экономической Зоне',
            q1_v4: 'Оффшорная компания',
            q1_v5: 'Нужна помощь для определения типа компании',
            label_2_1: 'Учредитель — физическое лицо?',
            label_2_2: 'Количество учредителей?',
            q2_v1: 'Да',
            q2_v2: 'Нет',
            q2_v3: 'Требуется помощь в определении',
            label_3_1: 'Гражданство',
            label_3_2: 'Количество директоров?',
            q3_v1: 'ОАЭ',
            q3_v2: 'Страны Персидского Залива',
            q3_v3: 'Другой страны',
            label_4_1: 'Укажите необходимое количество виз',
            q4_v1: 'Требуется помощь для определения необходимости визы',
            q5_v1: 'В ближайшие дни',
            q5_v2: 'В течении месяца',
            q5_v3: 'Прицениваюсь',
            label_6_1: 'Наименование компании',
            label_6_2: 'Количество сотрудников?',
            label_6_3: 'Вид деятельности компании',
            q6_v1: 'Введите наименование',
            q6_v3: 'Опишите в нескольких словах',
            label_7_1: 'Размер офисных помещений',
            label_7_2: 'Банковский счёт',
            label_7_3: 'Планируемый ежегодный оборот',
            q7_v1_1: 'Мне не нужен офис',
            q7_v1_2: 'Нужна помощь для определения',
            q7_v2: 'Требуется помощь при открытии счёта',
            q7_v3: 'Не знаю',
            yes: 'Да',
            label_connection: 'Выберите предпочитаемые способы связи',
            connection_call: 'Звонок',
            connection_sms: 'СМС',
            connection_whatsApp: 'WhatsApp',
            label_phone: 'Введите номер телефона и мы  свяжется с вами в течении 15 минут',
            alarm: 'Оставляя контактную информацию, вы соглашаетесь на обработку персональных данных',
            thanks_subtitle: 'Спасибо!',
            thanks_title: 'Ваша заявка принята',
            back_to_site: 'Перейти на сайт',
            alert_phone: 'Некорректно введен телефон',
            next: 'Далее →',
            modal_title: 'Заказать звонок',
            modal_intro: 'Заполните форму и&nbsp;мы свяжемся с&nbsp;вами в&nbsp;течение <span class="mark">5&nbsp;минут.</span>',
            send: 'Отправить',
            title_send: 'Cпасибо, заявка отправлена'
        }),
        new MLanguage('en').create({
            callBack: 'Order a call',
            title: 'SetUp your UAE Company',
            subtitle: 'Know how to register your business in the UAE from anywhere in the world - get a checklist with requirements and calculate your cost complimentary in few simple steps',
            btn_home: 'Get started!',
            btn_send: 'Get started!',
            site_link: 'Visit website',
            header_step: 'Question {0}',
            header_step_cont: 'Contacts',
            header_thank: 'Thank you',
            header_title_1: ' Please choose your legal structure',
            header_title_2: 'Info about the Shareholder',
            header_title_3: 'Info about the Directors',
            header_title_4: 'UAE Resident Visa for the Shareholders and Employees',
            header_title_5: 'When do you plan to submit your application for UAE company incorporation?',
            header_title_6: 'Tell us about your future business in the UAE',
            header_title_7: 'Other matters',
            header_title_8: 'Get checklist with requirements and cost involved complimentary from us',
            q1_v1: 'Limited Liability Partnership or Company',
            q1_v2: 'Branch or Representative Office',
            q1_v3: 'Freezone Company',
            q1_v4: 'Offshore Company',
            q1_v5: 'I need help to identify my legal structure',
            label_2_1: ' Is the Shareholder a natural person?',
            label_2_2: 'Number of Shareholders?',
            q2_v1: 'Yes',
            q2_v2: 'No',
            q2_v3: 'Assistance required',
            label_3_1: 'Country of Citizenship',
            label_3_2: 'Number of Directors?',
            q3_v1: 'UAE',
            q3_v2: 'GCC Countries',
            q3_v3: 'Other',
            label_4_1: 'Please indicate the required number of visas',
            q4_v1: 'Need help to determine the need for a visa',
            q5_v1: 'Within a few days',
            q5_v2: 'Within a month',
            q5_v3: 'No idea',
            label_6_1: ' Proposed Company name',
            label_6_2: 'Number of Employees?',
            label_6_3: 'Company activity',
            q6_v1: 'please enter a name',
            q6_v3: 'Please describe in a few words',
            label_7_1: ' Size of office premises (if required)',
            label_7_2: 'Bank account',
            label_7_3: 'Planned annual turnover',
            q7_v1_1: ' I don’t need office for my business',
            q7_v1_2: ' I need your advice to find best suited premises',
            q7_v2: 'Need assistance to open a bank account',
            q7_v3: 'I don’t know',
            yes: 'yes',
            label_connection: 'please choose preferred communication',
            connection_call: 'call',
            connection_sms: 'SMS',
            connection_whatsApp: 'WhatsApp',
            label_phone: 'Please enter your phone number and  we will get back to you within 15 minutes',
            alarm: ' By providing us with your contact details you agree for processing of your personal data',
            thanks_subtitle: 'THANK YOU',
            thanks_title: 'Your request has been accepted',
            back_to_site: 'Visit website',
            alert_phone: 'error input',
            next: 'Next →',
            modal_title: 'Request a call',
            modal_intro: 'Fill out the form and we will contact you within <span class="mark">5 minutes.</span>',
            send: 'Send',
            title_send: 'Thank you, the application has been sent'
        })
    ]
})
